### ISSUE TITLE
点击我的-推荐分享闪退

### ISSUE THREAD

**Issue by programmelearn** [HarmonyOS-Next/interview-handbook-project#9]
Error message:Cannot read property SharedData of undefined
SourceCode:
                const data = new systemShare.SharedData({
                                 ^
Stacktrace:
Cannot get SourceMap info, dump raw stack:
    at anonymous (products/phone/build/default/cache/default/default@CompileArkTS/esmodule/debug/features/mine/src/main/ets/views/MineComp.ts:390:34)
    at anonymous (products/phone/build/default/cache/default/default@CompileArkTS/esmodule/debug/features/mine/src/main/ets/views/MineComp.ts:154:33)

**Comment by zhousg** [comment]
if (systemShare?.SharedData) {
   // 分享逻辑 （模拟器不支持）
}
